export const STORE_DEFAULT_NAME = '__STATE_MACHINE__';
export const STATE_MACHINE_DEBUG_NAME = '___STATE_MACHINE_DEBUG__';
export const STATE_MACHINE_DEV_TOOL_CONFIG = '___STATE_MACHINE_DEV_CONFIG__';
